/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://lyi2qmdfpnhkbfrebbr7viq5hi.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-vnlwims655cadf6ahd7xqouhoe",
  aws_cognito_identity_pool_id:
    "us-east-1:d2d1bdc8-223d-47f0-8df0-0cf411635dd3",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_Ean7KGgTu",
  aws_user_pools_web_client_id: "1qt1s6spbb49sf5mlib2vthj2i",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket:
    "redditclone2481068871f7744358706595ed8df9f98180626-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
